### ISSUE TITLE
Crop and save bounding box libtorch c++

### ISSUE THREAD

**Issue by problemSolvingProgramming** [Hexmagic/libtorch_example#1]
Hi, I want to add crop and save bounding box libtorch c ++ to the following code, but unfortunately I do not know exactly, I can crop one person, but if there are several objects in an image, I can not crop or save them with different boundix. Thank you very much for helping us or writing the code.? https://github.com/Nebula4869/YOLOv5-LibTorch

**Comment by Hexmagic** [comment]
if you want save box to txt ,add bellow line to  YOLOv5LibTorch.cpp
```c++
#line 75
std::ofstream fout("label.txt");
#line 123
fout << left << "," << top << "," << right << "," << bottom << "," << score << "," << classID << std::endl;
#line 138
fout.close()
```
